dataAnalysis/histscenario/forms.py
from dataAnalysis import app
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SelectField, DateField, BooleanField
from wtforms.validators import DataRequired, Optional
from os.path import join, isfile
import os


choice = [('display', 'Select options'),('first', 1), ('second', 2), ('third', 3), ('forth',4), ('fifth',5), ('tenth', 10)]
choicePCFiles = [('','')]
choiceIdxFiles = [('','')]

def get_files():
	currentPath = os.getcwd()
	compFilePath = join(currentPath, 'dataAnalysis/static/compfiles')
	files = [f for f in os.listdir(compFilePath) if isfile(join(compFilePath, f))]
	#print "COMPARE FILES: ", files
	#choiceFiles = [('Select File for comparision','Select File for comparision')]
	for file in files:
		if 'PC' in file:
			choicePCFiles.append((file, file))
		elif 'indx' in file:
			choiceIdxFiles.append((file, file))

	#return choiceFiles

class HistScenarioForm(FlaskForm):
	"""docstring for HistScenarioForm"""
	default_scenario_set = BooleanField('Default Scenario Set', validators=[])
	scenario_set_name = StringField('Scenario set Name', validators=[Optional()])
	scenario_set_desc = TextAreaField('Descriptions', validators=[Optional()])
	lock_back_period = SelectField('Lock Back Period', choices=choice)
	start_date = DateField('Start Date', validators=[DataRequired()], format='%d/%m/%Y')
	end_date = DateField('End Date', validators=[DataRequired()], format='%d/%m/%Y')
	effective_date = DateField('Effective Date', validators=[Optional()], format='%d/%m/%Y')
	expiry_date = DateField('Expiry Date', validators=[Optional()], format='%d/%m/%Y')
	liquidation_horizon = SelectField('Liquidation Horizon', choices=choice)
	liquidation_period = SelectField('Liquidation Period', choices=choice)
	
class RunAnalysisForm(FlaskForm):
	"""docstring for RunAnalysisForm"""
	get_files()
	currentPcdfFile = SelectField('Current PCDF File:', choices=choicePCFiles)
	previousPcdfFile = SelectField('Previous PCDF File:', choices=choicePCFiles)

	currentIdxFile = SelectField('Current Idx File:', choices=choiceIdxFiles)
	previousIdxFile = SelectField('Previous Idx File:', choices=choiceIdxFiles)

	

dataAnalysis/histscenario/controllers.py
from flask import render_template, Blueprint, request, make_response
from dataAnalysis.histscenario.forms import HistScenarioForm, RunAnalysisForm
from dataAnalysis import app
import pandas as pd
import pymssql
import os


##############################################################################
histscenario = Blueprint('histscenario', __name__, url_prefix='/histscenario')
##############################################################################


@histscenario.route('/runanalysis', methods=['GET', 'POST'])
def run_analysis():
	form = RunAnalysisForm()
	title = "Run Comparision Analysis"

	if request.method == 'POST' and form.validate_on_submit():
		curPcdfFile = form.currentPcdfFile.data
		prePcdfFile = form.previousPcdfFile.data
		curIdxFile = form.currentIdxFile.data
		preIdxFile = form.previousIdxFile.data

		path = os.getcwd() + '/dataAnalysis/static/compfiles'
		preMonPCDF = pd.read_excel(os.path.join(path, prePcdfFile), sheetname = "Sheet1")
		newMonPCDF = pd.read_excel(os.path.join(path, curPcdfFile), sheetname = "Sheet1")
		preMonIdxDF = pd.read_excel(os.path.join(path, preIdxFile), sheetname = "Sheet1")
		newMonIdxDF = pd.read_excel(os.path.join(path, curIdxFile), sheetname = "Sheet1")

		preMonPCDF.reset_index(inplace = True)
		newMonPCDF.reset_index(inplace = True)
		preMonIdxDF.reset_index(inplace = True)
		newMonIdxDF.reset_index(inplace = True)
		preMonPCDF.rename(columns = {"index": "Date"}, inplace = True)
		newMonPCDF.rename(columns = {"index": "Date"}, inplace = True)
		preMonIdxDF.rename(columns = {"index": "Date"}, inplace = True)
		newMonIdxDF.rename(columns = {"index": "Date"}, inplace = True)

		missDF = preMonPCDF[~preMonPCDF.Date.isin(newMonPCDF.Date.values)]
		newDF = newMonPCDF[~newMonPCDF.Date.isin(preMonPCDF.Date.values)]

		#rows = []
		newRows = []
		missRows = []
		if not newDF.empty:
		    newRows = makeAnalysisData(newDF, newMonIdxDF, 'new')
		if not missDF.empty:
		    missRows = makeAnalysisData(missDF, preMonIdxDF, 'miss')

		if newRows and missRows:
			rows = newRows + missRows
		elif newRows:
			rows = newRows
		elif missRows:
			rows = missRows


		return render_template("histscenario/disp_analysis.html",rows = rows)

	return (render_template('histscenario/run_analysis.html', form=form, title=title))


@histscenario.route('/create', methods=['GET', 'POST'])
def create():
	form = HistScenarioForm()
	title = "create Historical scenario Data"
	choices = {'first': 1, 'second': 2, 'third': 3, 'fourth': 4, 'fifth': 5, 'tenth': 10}

	if request.method == 'POST' and form.validate_on_submit():
		bus_dt = form.start_date.data
		liq_period = choices.get(request.form.get('liquidation_period'), 0)
		look_back_period = choices.get(request.form.get('lock_back_period'), 0)

		cur = getConnection()
		#cur.execute("select * from yld_crv_hist_v")
		#cur.execute("EXEC s_SGD_CPA_raw_data_R @bus_dt = '1990-01-10', @liq_period = 10, @look_back_period = 5")
		cur.execute("EXEC s_SGD_CPA_raw_data_R @bus_dt = '{}', @liq_period = {}, @look_back_period = {}".format(bus_dt, liq_period, look_back_period))

		rows = cur.fetchall();

		# print app.config['USERNAME']
		# print app.config['PASSWORD']
		print rows
		return render_template("histscenario/disp_create.html",rows = rows)

	return (render_template('histscenario/create.html', form=form, title=title))


@histscenario.route('/add', methods=['GET', 'POST'])
def add():
	form = HistScenarioForm(request.form)
	title = "Add Historical Scenario data"

	if request.method == 'POST' and form.validate_on_submit():
		return "Under construction"
	return (make_response(render_template('histscenario/form.html', form=form, title=title)))


@histscenario.route('/import', methods=['GET', 'POST'])
def histImport():
	return "This page is under construction....."
	#return render_template('histscenario/import.html')

@histscenario.route('/addRemove', methods=['GET', 'POST'])
def addRemove():
	return "This page is under construction....."
	#return render_template('histscenario/addRemove.html')

def getConnection():
	con = pymssql.connect(  app.config['HOSTNAME'],
								app.config['USERNAME'],
								app.config['PASSWORD'],
								app.config['DBNAME'],
								app.config['PORT'])

	cursor = con.cursor()

	return cursor

def makeAnalysisData(newmissdf, idxDF, sln):
	data = []
	for index, row in newmissdf.iterrows():
		date = row['Date']
		driver = row['driver']
		idxDF.sort_values(by=[str(driver)], ascending = True, inplace = True)
		dfLength = len(idxDF.index)

		#print date
		# get rank
		rtext = getRank(idxDF, driver, date, dfLength)

		data.append((str(sln),
					str(date),
					str(row['y1']),
					str(row['y2']),
					str(row['y3']),
					str(row['y5']),
					str(row['y7']),
					str(row['y10']),
					str(row['y20']),
					str(row['y30']),
					str(rtext)))
	return data

def getRank(df, driver, date, dfLength):
    rank = ''
    for idx, r in df.iterrows():
        rr = r['Date']
        if str(date) == str(rr):
            if idx > dfLength / 2:
                rank = dfLength - idx
                rank = '-' + str(rank)
            else:
                rank = idx

    rtext = driver + " Relative ranking (" + rank + ")"
    return rtext

dataAnalysis/templates/histscenario/create.html
{% extends 'base.html' %}
{% import "macros.html" as macros %}

{% block scripts %}
    {{ super() }}

    <script>
      $( function() {
        $( ".dtpick" ).datepicker();
      } );
    </script>

{% endblock %}
{% block  content %}
{% include 'macros.html' %}

<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <div class="well well-lg" style="background-color: lightgrey">
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-md-10">
                    <div class="row">
                        <div align="center">
                            <u><h2>Provide details to download</h2></u>
                        </div>
                        {% if "create" in title %}
                            <form class="form-horizontal" method="POST" name="url" action="{{url_for('histscenario.create')}}">
                        {% endif %}

                            {{form.hidden_tag()}}

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.default_scenario_set, with_label=True, placeholder="", class_="form-control")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.scenario_set_name, with_label=True, placeholder="scenario name", class_="form-control")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.scenario_set_desc, with_label=True, placeholder="description", class_="form-control")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.lock_back_period, with_label=True, placeholder="", class_="form-control")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.start_date, with_label=True, placeholder="mm/dd/yyyy", class_="dtpick")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.end_date, with_label=True, placeholder="mm/dd/yyyy", class_="dtpick")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.effective_date, with_label=True, placeholder="mm/dd/yyyy", class_="dtpick")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.expiry_date, with_label=True, placeholder="mm/dd/yyyy", class_="dtpick")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.liquidation_horizon, with_label=True, placeholder="", class_="form-control")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.liquidation_period, with_label=True, placeholder="", class_="form-control")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 50px">
                                <div class="col-md-4"></div>
                                <div class="col-md-4">
                                    <button type="submit" class="btn btn-primary btn-block">Submit</button>
                                </div>
                            </div>
                            {# {{form.errors}} #}
                            </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</div>

{% endblock %}

dataAnalysis/templates/histscenario/disp_analysis.html
{% extends 'base.html' %}
{% import "macros.html" as macros %}
{% block scripts %}
    {{ super() }}

    <script type="text/javascript">
      $(document).ready(function(){
         var table = $('#urls').DataTable();
         $("#urls thead th").each( function ( i ){
            var name = table.column( i ).header();
            var spanelt = document.createElement( "button" );
            spanelt.innerHTML = name.innerHTML;

            $(spanelt).addClass("colvistoggle");
            $(spanelt).attr("colidx", i);

            $(spanelt).on( 'click', function (e) {
               e.defaultPrevented();
               // get column API object
               var column = table.column( $(this).attr('colidx') );
               // toggle the visivility
               column.visible( ! column.visible() );
            });
            $("#colvis").append($(spanelt));
         });
      });

    </script>

{% endblock %}
{% block  content %}

<div class="row">
   <div class="col-lg-1"></div>
   <div class="col-lg-10">
      <div class="well well-lg" style="width:100%;overflow-x: auto;overflow-y: auto;">
         <div class="table-responsive">
            <table id="urls" name='urls' class="display" cellspacing="0" width="100%">
               <thead>
                  <th>Selection</th>
                  <th>GSD</th>
                  <th>y1</th>
                  <th>y2</th>
                  <th>y3</th>
                  <th>y5</th>
                  <th>y7</th>
                  <th>y10</th>
                  <th>y20</th>
                  <th>y30</th>
                  <th>Driver</th>
               </thead>
               <tfoot>
                  <th>Selection</th>
                  <th>GSD</th>
                  <th>y1</th>
                  <th>y2</th>
                  <th>y3</th>
                  <th>y5</th>
                  <th>y7</th>
                  <th>y10</th>
                  <th>y20</th>
                  <th>y30</th>
                  <th>Driver</th>
               </tfoot>
               <tbody>
                  {%- for row in rows %}
                     <tr>
                        <td>{{row[0]}}</td>
                        <td>{{row[1]}}</td>
                        <td>{{row[2]}}</td>
                        <td>{{row[3]}}</td>
                        <td>{{row[4]}}</td>
                        <td>{{row[5]}}</td>
                        <td>{{row[6]}}</td>
                        <td>{{row[7]}}</td>
                        <td>{{row[8]}}</td>
                        <td>{{row[9]}}</td>
                        <td>{{row[10]}}</td>
                     </tr>
                  {% endfor %}
               </tbody>
            </table>
         </div>
      </div>
   </div>
</div>

{% endblock %}

dataAnalysis/templates/histscenario/disp_create.html
{% extends 'base.html' %}
{% import "macros.html" as macros %}
{% block scripts %}
    {{ super() }}

    <script type="text/javascript">
      $(document).ready(function(){
         var table = $('#urls').DataTable();
         $("#urls thead th").each( function ( i ){
            var name = table.column( i ).header();
            var spanelt = document.createElement( "button" );
            spanelt.innerHTML = name.innerHTML;

            $(spanelt).addClass("colvistoggle");
            $(spanelt).attr("colidx", i);

            $(spanelt).on( 'click', function (e) {
               e.defaultPrevented();
               // get column API object
               var column = table.column( $(this).attr('colidx') );
               // toggle the visivility
               column.visible( ! column.visible() );
            });
            $("#colvis").append($(spanelt));
         });
      });

    </script>

{% endblock %}
{% block  content %}

<div class="row">
   <div class="col-lg-1"></div>
   <div class="col-lg-10">
      <div id="colvis"></div>
   </div>
</div>
<div class="row">
   <div class="col-lg-1"></div>
   <div class="col-lg-10">
      <div class="well well-lg" style="width:100%;overflow-x: auto;overflow-y: auto;">
         <div class="table-responsive">
            <table id="urls" name='urls' class="display" cellspacing="0" width="100%">
               <thead>
                  <td>Date</td>
                  <td>y1</td>
                  <td>y2</td>
                  <td>y3</td>
                  <td>y5</td>
                  <td>y7</td>
                  <td>y10</td>
                  <td>y20</td>
                  <td>y30</td>
               </thead>
               <tfoot>
                  <td>Date</td>
                  <td>y1</td>
                  <td>y2</td>
                  <td>y3</td>
                  <td>y5</td>
                  <td>y7</td>
                  <td>y10</td>
                  <td>y20</td>
                  <td>y30</td>
               </tfoot>
               <tbody>
                  {%- for row in rows %}
                     <tr>
                        <td>{{row[0]}}</td>
                        <td>{{row[1]}}</td>
                        <td>{{row[2]}}</td>
                        <td>{{row[3]}}</td>
                        <td>{{row[4]}}</td>
                        <td>{{row[5]}}</td>
                        <td>{{row[6]}}</td>
                        <td>{{row[7]}}</td>
                        <td>{{row[8]}}</td>
                     </tr>
                  {% endfor %}
               </tbody>
            </table>
         </div>
      </div>
   </div>
</div>

{% endblock %}

dataAnalysis/templates/histscenario/form.html
{% extends 'base.html' %}
{% import "macros.html" as macros %}

{% block scripts %}
    {{ super() }}

    <script>
      $( function() {
        $( ".dtpick" ).datepicker();
      } );
    </script>

{% endblock %}
{% block  content %}
{% include 'macros.html' %}

<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <div class="well well-lg" style="background-color: lightgrey">
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-md-10">
                    <div class="row">
                        <div align="center">
                            <u><h2>Provide details to download</h2></u>
                        </div>
                        {% if "create" in title %}
                            <form class="form-horizontal" method="POST" name="url" action="{{url_for('histscenario.create')}}">
                        {% endif %}

                            {{form.hidden_tag()}}

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.default_scenario_set, with_label=True, placeholder="", class_="form-control")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.scenario_set_name, with_label=True, placeholder="scenario name", class_="form-control")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.scenario_set_desc, with_label=True, placeholder="description", class_="form-control")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.lock_back_period, with_label=True, placeholder="", class_="form-control")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.start_date, with_label=True, placeholder="mm/dd/yyyy", class_="dtpick")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.end_date, with_label=True, placeholder="mm/dd/yyyy", class_="dtpick")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.effective_date, with_label=True, placeholder="mm/dd/yyyy", class_="dtpick")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.expiry_date, with_label=True, placeholder="mm/dd/yyyy", class_="dtpick")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.liquidation_horizon, with_label=True, placeholder="", class_="form-control")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.liquidation_period, with_label=True, placeholder="", class_="form-control")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 50px">
                                <div class="col-md-4"></div>
                                <div class="col-md-4">
                                    <button type="submit" class="btn btn-primary btn-block">Submit</button>
                                </div>
                            </div>
                            {# {{form.errors}} #}
                            </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</div>

{% endblock %}

dataAnalysis/templates/histscenario/list.html
{% extends 'base.html' %}
{% import "macros.html" as macros %}
{% block scripts %}
    {{ super() }}

    <script type="text/javascript">
      $(document).ready(function(){
         var table = $('#urls').DataTable();
         $("#urls thead th").each( function ( i ){
            var name = table.column( i ).header();
            var spanelt = document.createElement( "button" );
            spanelt.innerHTML = name.innerHTML;

            $(spanelt).addClass("colvistoggle");
            $(spanelt).attr("colidx", i);

            $(spanelt).on( 'click', function (e) {
               e.defaultPrevented();
               // get column API object
               var column = table.column( $(this).attr('colidx') );
               // toggle the visivility
               column.visible( ! column.visible() );
            });
            $("#colvis").append($(spanelt));
         });
      });

    </script>

{% endblock %}
{% block  content %}

<div class="row">
   <div class="col-lg-1"></div>
   <div class="col-lg-10">
      <div id="colvis"></div>
   </div>
</div>
<div class="row">
   <div class="col-lg-1"></div>
   <div class="col-lg-10">
      <div class="well well-lg" style="width:100%;overflow-x: auto;overflow-y: auto;">
         <div class="table-responsive">
            <table id="urls" name='urls' class="display" cellspacing="0" width="100%">
               <thead>
                  <td>Date</td>
                  <td>y1</td>
                  <td>y2</td>
                  <td>y3</td>
                  <td>y5</td>
                  <td>y7</td>
                  <td>y10</td>
                  <td>y20</td>
                  <td>y30</td>
               </thead>
               <tfoot>
                  <td>Date</td>
                  <td>y1</td>
                  <td>y2</td>
                  <td>y3</td>
                  <td>y5</td>
                  <td>y7</td>
                  <td>y10</td>
                  <td>y20</td>
                  <td>y30</td>
               </tfoot>
               <tbody>
                  {%- for row in rows %}
                     <tr>
                        <td>{{row[0]}}</td>
                        <td>{{row[1]}}</td>
                        <td>{{row[2]}}</td>
                        <td>{{row[3]}}</td>
                        <td>{{row[4]}}</td>
                        <td>{{row[5]}}</td>
                        <td>{{row[6]}}</td>
                        <td>{{row[7]}}</td>
                        <td>{{row[8]}}</td>
                     </tr>
                  {% endfor %}
               </tbody>
            </table>
         </div>
      </div>
   </div>
</div>

{% endblock %}

dataAnalysis/templates/histscenario/run_analysis.html
{% extends 'base.html' %}
{% import "macros.html" as macros %}

{% block scripts %}
    {{ super() }}

{% endblock %}
{% block  content %}
{% include 'macros.html' %}

<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <div class="well well-lg" style="background-color: lightgrey">
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-md-10">
                    <div class="row">
                        <div align="center">
                            <u><h2>Provide details for comparision analysis</h2></u>
                        </div>
                        {% if "Run" in title %}
                            <form class="form-horizontal" method="POST" name="url" action="{{url_for('histscenario.run_analysis')}}">
                        {% endif %}

                            {{form.hidden_tag()}}

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.currentPcdfFile, with_label=True, placeholder="", class_="form-control")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.previousPcdfFile, with_label=True, placeholder="", class_="form-control")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.currentIdxFile, with_label=True, placeholder="", class_="form-control")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.previousIdxFile, with_label=True, placeholder="", class_="form-control")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 50px">
                                <div class="col-md-4"></div>
                                <div class="col-md-4">
                                    <button type="submit" class="btn btn-primary btn-block">Submit</button>
                                </div>
                            </div>
                            {# {{form.errors}} #}
                            </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</div>

{% endblock %}