dataAnalysis/download/forms.py
from dataAnalysis import app
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SelectField, DateField, BooleanField
from wtforms.validators import DataRequired, Optional

# choice = [('display', 'Select locl back period'),('first', 1), ('second', 2), ('third', 3), ('forth',4), ('fifth',5), ('tenth', 10)]

# class DownloadForm(FlaskForm):
# 	default_scenario_set = BooleanField('Default Scenario Set', validators=[])
# 	scenario_set_name = StringField('Scenario set Name', validators=[Optional()])
# 	scenario_set_desc = TextAreaField('Descriptions', validators=[Optional()])
# 	lock_back_period = SelectField('Lock Back Period', choices=choice)
# 	start_date = DateField('Start Date', validators=[DataRequired()], format='%d/%m/%Y')
# 	end_date = DateField('End Date', validators=[DataRequired()], format='%d/%m/%Y')
# 	effective_date = DateField('Effective Date', validators=[Optional()], format='%d/%m/%Y')
# 	expiry_date = DateField('Expiry Date', validators=[Optional()], format='%d/%m/%Y')
# 	liquidation_horizon = SelectField('Liquidation Horizon', choices=choice)
# 	liquidation_period = SelectField('Liquidation Period', choices=choice)
	

class DownloadCDCPForm(FlaskForm):
	start_date = StringField("Start Date", validators=[DataRequired()])
	end_date = StringField("End Date", validators=[DataRequired()])

dataAnalysis/download/controllers.py
from flask import render_template, Blueprint, request, make_response
from dataAnalysis.download.forms import DownloadCDCPForm
from dataAnalysis import app, db
from datetime import date
import traceback
import requests
import pymssql
import os
import re

##################################################################
download = Blueprint('download', __name__, url_prefix='/download')
##################################################################


@download.route('/downloadcdcp', methods=['GET', 'POST'])
def download_cdcp():
	form = DownloadCDCPForm()
	title = 'Download CD/CP data'

	if request.method == 'POST' and form.validate_on_submit():
		start_date = form.start_date.data
		end_date = form.end_date.data
		sdate = start_date.split('/')
		edate = end_date.split('/')
		sd = re.sub(r'/','', start_date)
		ed = re.sub(r'/','', end_date)
		file = 'dataAnalysis/static/downloadFiles/FRB_H15_' + sd + '_' + ed + '.csv'
		path = os.getcwd()
		fname = os.path.join(path, file)
		rows = []
		header = []

		url = get_frb_url(dtStart=date(int(sdate[2]), int(sdate[0]), int(sdate[1])),
						  dtEnd=date(int(edate[2]), int(edate[0]), int(edate[1])))
		#url = get_frb_url(dtStart=date(2017, 11, 02), dtEnd=date(2017, 11, 15))
		#frb_site = urllib.urlopen(url)
		frb_site = requests.get(url)
		#text = frb_site.read().strip()
		text = frb_site.text
		#print "TEXT: ", frb_site.text

		with open(fname, 'w') as wf:
			wf.write(text)

		with open(fname, 'r') as rf:
			cnt = 0
			try:
				con = getConnection()
				cursor = con.cursor()
				for line in rf:
					cnt += 1
					if cnt < 6:
						continue
					elif cnt == 6:
						data = line.split(',')
						header.extend([data[0], data[1], data[2]])
					else:
						data = line.split(',')
						rows.append((data[0], data[1], data[2]))

						dly_dt = 'NULL' if 'ND' in data[0] else data[0]
						fcp_val =  'NULL' if 'ND' in data[1] else data[1]
						nfcp_val = 'NULL' if 'ND' in data[2] else data[2]
						
						cursor.execute("INSERT INTO hist_cd_cp VALUES ('{}', {}, {})".format(dly_dt, fcp_val, nfcp_val))
						con.commit()
			except Error as e:
				app.logger.warning(e)
				print e
			finally:
				cursor.close()
				con.close()
		#print rows
		return render_template("download/list.html", rows=rows, header=header)

	return (render_template('download/form.html', form=form, title=title))

@download.route("/database")
def getDatabase():
	return "This page is under construction....."
	#return render_template('histscenario/database.html')

@download.route("/excel")
def getExcel():
	return "This page is under construction....."
	#return render_template('histscenario/excel.html')

def get_frb_url(dtStart, dtEnd):
	downloadUrl = app.config['DOWNLOAD_URL']

	url = downloadUrl % (dtStart.strftime('%m/%d/%Y'), dtEnd.strftime('%m/%d/%Y'))

	return url

def getConnection():
	con = pymssql.connect(  	app.config['HOSTNAME'],
								app.config['USERNAME'],
								app.config['PASSWORD'],
								'IRS_DFM',
								app.config['PORT'])

	return con

dataAnalysis/templates/download/form.html
{% extends 'base.html' %}
{% import "macros.html" as macros %}

{% block scripts %}
    {{ super() }}

    <script>
      $( function() {
        $( ".dtpick" ).datepicker();
      } );
    </script>

{% endblock %}
{% block  content %}
{% include 'macros.html' %}

<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <div class="well well-lg" style="background-color: lightgrey">
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-md-10">
                    <div class="row">
                        <div align="center">
                            <u><h2>Download CD/CP data</h2></u>
                        </div>
                        {% if "Download" in title %}
                            <form class="form-horizontal" method="POST" name="url" action="{{url_for('download.download_cdcp')}}">
                        {% endif %}

                            {{form.hidden_tag()}}


                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.start_date, with_label=True, placeholder="mm/dd/yyyy", class_="dtpick")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.end_date, with_label=True, placeholder="mm/dd/yyyy", class_="dtpick")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 50px">
                                <div class="col-md-4"></div>
                                <div class="col-md-4">
                                    <button type="submit" class="btn btn-primary btn-block">Submit</button>
                                </div>
                            </div>
                            {# {{form.errors}} #}
                            </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</div>

{% endblock %}

dataAnalysis/templates/download/list.html
{% extends 'base.html' %}
{% import "macros.html" as macros %}
{% block scripts %}
    {{ super() }}

    <script type="text/javascript">
      $(document).ready(function(){
         var table = $('#urls').DataTable();
         $("#urls thead th").each( function ( i ){
            var name = table.column( i ).header();
            var spanelt = document.createElement( "button" );
            spanelt.innerHTML = name.innerHTML;

            $(spanelt).addClass("colvistoggle");
            $(spanelt).attr("colidx", i);

            $(spanelt).on( 'click', function (e) {
               e.defaultPrevented();
               // get column API object
               var column = table.column( $(this).attr('colidx') );
               // toggle the visivility
               column.visible( ! column.visible() );
            });
            $("#colvis").append($(spanelt));
         });
      });

    </script>

{% endblock %}
{% block  content %}

<div class="row">
   <div class="col-lg-1"></div>
   <div class="col-lg-10">
      <div id="colvis"></div>
   </div>
</div>
<div class="row">
   <div class="col-lg-1"></div>
   <div class="col-lg-10">
      <div class="well well-lg" style="width:100%;overflow-x: auto;overflow-y: auto;">
         <div class="table-responsive">
            <table id="urls" name='urls' class="display" cellspacing="0" width="100%">
               <thead>
                  <td>{{header[0]}}</td>
                  <td>{{header[1]}}</td>
                  <td>{{header[2]}}</td>
               </thead>
               <tfoot>
                  <td>{{header[0]}}</td>
                  <td>{{header[1]}}</td>
                  <td>{{header[2]}}</td>
               </tfoot>
               <tbody>
                  {%- for row in rows %}
                     <tr>
                        <td>{{row[0]}}</td>
                        <td>{{row[1]}}</td>
                        <td>{{row[2]}}</td>
                     </tr>
                  {% endfor %}
               </tbody>
            </table>
         </div>
      </div>
   </div>
</div>

{% endblock %}